sonar.projectKey=Evref-BL_DevNexus-Pharo
sonar.projectName=DevNexus-Pharo
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.exclusions=dist/**,node_modules/**,coverage/**,.scannerwork/**,.quality/**,.dev-nexus/**,.agents/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
