import {
  mcpPharoDomainSkill,
  skillText,
} from "../mcpPharoDomainSkillSupport.js";

export const pharoCiReproSkill = mcpPharoDomainSkill(
    "pharo-ci-repro",
    "Recreate Pharo smalltalkCI and GitHub Actions conditions locally with Docker, capture logs from flaky Pharo CI failures, isolate failing Smalltalk test classes or methods, and distinguish project failures from Pharo VM/Iceberg/libgit2/external-service issues. Use when asked to reproduce, debug, stress, or understand Pharo CI failures locally, especially with smalltalkCI, Docker, Pharo version matrices, intermittent segfaults, or GitHub Actions logs.",
    {
      "SKILL.md": skillText([
        "---",
        "name: pharo-ci-repro",
        "description: Recreate Pharo smalltalkCI and GitHub Actions conditions locally with Docker, capture logs from flaky Pharo CI failures, isolate failing Smalltalk test classes or methods, and distinguish project failures from Pharo VM/Iceberg/libgit2/external-service issues. Use when asked to reproduce, debug, stress, or understand Pharo CI failures locally, especially with smalltalkCI, Docker, Pharo version matrices, intermittent segfaults, or GitHub Actions logs.",
        "---",
        "",
        "# Pharo CI Repro",
        "",
        "## Overview",
        "",
        "Use this skill to reproduce a Pharo CI run locally with Docker and",
        "smalltalkCI, then preserve enough evidence to understand failures that are",
        "hard to diagnose from GitHub logs alone.",
        "",
        "Prefer matching the CI runner first, then narrowing. Do not jump straight to a",
        "hand-written Pharo script unless smalltalkCI itself is not involved in the",
        "failure.",
        "",
        "## Workflow",
        "",
        "1. Identify the CI facts:",
        "   - Pharo platform, for example `Pharo64-13` or `Pharo64-12`.",
        "   - smalltalkCI config path, usually `.smalltalk.ston`.",
        "   - Branch/commit under test.",
        "   - Whether the failure happens during image download, dependency load, project",
        "     load, tests, coverage, or teardown.",
        "",
        "2. Check the local repo state:",
        "   - Run `git status --short --branch`.",
        "   - If reproducing GitHub exactly, use a clean checkout of the failing commit.",
        "   - If testing a local fix, copy the working tree into a scratch directory and",
        "     accept that smalltalkCI may print harmless \"not a git repository\" messages",
        "     if `.git` is excluded.",
        "",
        "3. Run a full local Docker reproduction:",
        "   - Use `scripts/run-smalltalkci-docker.sh` when available.",
        "   - Store logs outside the repo, usually under `/tmp`.",
        "   - Keep the first failing log; do not overwrite it during later narrowing.",
        "",
        "4. Narrow only after one faithful run:",
        "   - Create a temporary `.smalltalk-*.ston` that loads the same baseline but",
        "     runs a single suspect class or package.",
        "   - Repeat the focused run a few times for flakes.",
        "   - Compare crash stacks across failures. For VM crashes, the Smalltalk stack",
        "     just before the native stack is often the clue.",
        "",
        "5. Decide the diagnosis class:",
        "   - Project failure: deterministic Smalltalk failure/error with useful stack.",
        "   - Compatibility failure: load/test failure varies by Pharo version and names",
        "     missing globals/selectors/classes.",
        "   - Native/VM failure: segfault, stack overflow aftermath, or C stack in VM,",
        "     libgit2, FFI, Cairo, etc.",
        "   - External factor: download timeout, GitHub/network/auth/server issue before",
        "     project code runs.",
        "",
        "6. Verify the fix against all relevant Pharo versions before reporting:",
        "   - Run the fixed full suite for every CI platform touched by the change.",
        "   - For flakes, also rerun the focused suspect class/method.",
        "",
        "## Helper Script",
        "",
        "Run:",
        "",
        "```sh",
        "user/skills/pharo-ci-repro/scripts/run-smalltalkci-docker.sh \\",
        "  --repo /path/to/repo \\",
        "  --platform Pharo64-13 \\",
        "  --attempts 3",
        "```",
        "",
        "Useful flags:",
        "",
        "- `--spec .smalltalk-editrepo.ston` to run a focused temporary config.",
        "- `--out /tmp/my-repro` to choose the scratch/log directory.",
        "- `--include-git` to copy `.git` too. Use only for ordinary checkouts, not",
        "  worktrees whose `.git` file points outside the copied tree.",
        "- `--keep-going` to continue after failures and collect several failing logs.",
        "",
        "The script stops at the first failure by default and prints the log path.",
        "",
        "## Pharo-Specific Guidance",
        "",
        "Read `references/pharo-smalltalkci.md` when diagnosing a captured log,",
        "especially for Pharo 13, Iceberg, libgit2, or image/cache issues.",
        "",
        "Watch for these local reproduction traps:",
        "",
        "- The Docker image `hpiswa/smalltalkci:24.04` may run as `linux/amd64`; on Apple",
        "  Silicon, pass Docker's `--platform linux/amd64`.",
        "- Missing SSH keys in Docker often produce Metacello/Iceberg auth warnings and",
        "  HTTPS fallback. That can still match GitHub closely enough if dependencies",
        "  load.",
        "- A scratch copy without `.git` may print Git discovery warnings before Pharo",
        "  starts. Treat them as noise unless the CI failure itself involves Git metadata.",
        "- smalltalkCI can reuse caches inside one container, but separate Docker runs",
        "  usually redownload Pharo images/VMs. This is slower but closer to GitHub.",
        "",
        "## Reporting",
        "",
        "Report:",
        "",
        "- exact command(s) run;",
        "- Pharo image build and VM version from the log;",
        "- first failing phase;",
        "- key Smalltalk and native stack frames;",
        "- log paths;",
        "- what was changed or ruled out;",
        "- verification commands and results.",
        "",
        "Keep conclusions cautious for native crashes. Say \"triggered by our test path\"",
        "when the evidence points to an upstream VM/libgit2 issue but the project can",
        "avoid the unstable path.",
      ]),
      "agents/openai.yaml": skillText([
        "interface:",
        "  display_name: \"Pharo CI Repro\"",
        "  short_description: \"Reproduce Pharo CI locally\"",
        "  default_prompt: \"Use $pharo-ci-repro to recreate a failing Pharo smalltalkCI run locally and capture logs.\"",
      ]),
      "references/pharo-smalltalkci.md": skillText([
        "# Pharo smalltalkCI Log Reading Notes",
        "",
        "Use this reference after a local Docker/smalltalkCI run has produced logs.",
        "",
        "## Phase Boundaries",
        "",
        "smalltalkCI logs usually split into:",
        "",
        "1. Preparing folders.",
        "2. Starting Pharo build.",
        "3. Downloading image and VM.",
        "4. Preparing image and loading SmalltalkCI.",
        "5. Loading project.",
        "6. Testing project.",
        "7. Coverage/upload/teardown.",
        "",
        "If the crash happens after `Testing project...`, project code loaded. If it",
        "happens during `Loading project...`, inspect the last Metacello package loaded",
        "and the first missing global/class/selector.",
        "",
        "## Useful Evidence To Extract",
        "",
        "- `Image Information`, including `Pharo13.1.0SNAPSHOT` or similar.",
        "- Build information SHA.",
        "- VM version, when printed.",
        "- The first test class/method named before a failure.",
        "- The first Smalltalk exception, before any secondary cleanup failure.",
        "- For segfaults, both the native C frames and the Smalltalk frames immediately",
        "  above the crash.",
        "",
        "## Focused Config Pattern",
        "",
        "To narrow a failing class while preserving the same load path, create a",
        "temporary config next to `.smalltalk.ston`:",
        "",
        "```ston",
        "SmalltalkCISpec {",
        "  #loading : [",
        "    SCIMetacelloLoadSpec {",
        "      #baseline : 'MyProject',",
        "      #directory : 'src',",
        "      #ignoreImage : true,",
        "      #onConflict : #useIncoming,",
        "      #onUpgrade : #useIncoming",
        "    }",
        "  ],",
        "  #testing : {",
        "    #classes : [",
        "      #MyProjectSuspectTest",
        "    ],",
        "    #hidePassingTests : true,",
        "    #failOnZeroTests : true",
        "  }",
        "}",
        "```",
        "",
        "Adjust the baseline, directory, and class for the project under test.",
        "",
        "## Pharo 13 / Iceberg / libgit2 Pattern",
        "",
        "In a Pharo MCP investigation on 2026-05-16, a P13 flaky CI crash reproduced",
        "locally inside Docker. It was not a dependency download issue: loading",
        "completed and testing had started.",
        "",
        "Crash signatures included:",
        "",
        "- C stack in `libgit2.so.1.4.4`",
        "- `git_repository_head_unborn`",
        "- `git_commit_lookup`",
        "- Smalltalk frames through `IceLibgitRepository`, `IceRepository>>headCommit`,",
        "  or `IceRepository>>validateCanCommit`",
        "- Test frames in a repository-management test",
        "",
        "The practical mitigation was to avoid unnecessary test-side `repository",
        "headCommit` reads and skip a P13 test that deliberately forced empty libgit2",
        "config values for a P12-only fallback path.",
        "",
        "General lesson: if a Pharo 13 Linux CI segfault points into libgit2 while",
        "testing fresh temporary repositories, treat it as a native stability surface.",
        "Avoid poking Iceberg head/commit metadata in tests unless the assertion is",
        "essential.",
        "",
        "## Interpreting Common Noise",
        "",
        "- `fatal: not a git repository`: often harmless when running smalltalkCI from a",
        "  scratch copy without `.git`. It matters only if the failing behavior depends",
        "  on Git metadata.",
        "- Metacello SSH authentication warnings followed by HTTPS fallback: often",
        "  harmless in Docker if the dependency eventually loads.",
        "- `StackOverflow` after a segfault: often VM aftermath, not the root cause.",
        "- `NewUndeclaredWarning`: can be benign during dependency load, but if it names",
        "  a project class/global required by the current package, investigate.",
        "",
        "## Verification Discipline",
        "",
        "After a fix:",
        "",
        "- Run the failing Pharo platform full suite.",
        "- Run adjacent supported platforms, usually P12 and P13 for MCP.",
        "- Run focused repeats for the flaky class/method if the original failure was",
        "  intermittent.",
        "- Keep the captured failing log path in the report.",
      ]),
      "scripts/run-smalltalkci-docker.sh": skillText([
        "#!/usr/bin/env bash",
        "set -u",
        "",
        "usage() {",
        "  cat <<'USAGE'",
        "Usage:",
        "  run-smalltalkci-docker.sh --repo REPO_DIR [options]",
        "",
        "Options:",
        "  --repo DIR          Source repository or working tree to test.",
        "  --platform NAME    smalltalkCI platform, default Pharo64-13.",
        "  --spec FILE        smalltalkCI spec file, default .smalltalk.ston.",
        "  --attempts N       Number of attempts, default 1.",
        "  --out DIR          Scratch/log directory, default /tmp/pharo-ci-repro-<timestamp>.",
        "  --image IMAGE      Docker image, default hpiswa/smalltalkci:24.04.",
        "  --include-git      Copy .git into each scratch tree.",
        "  --keep-going       Continue after failures instead of stopping at first one.",
        "  --help             Show this help.",
        "",
        "Each attempt gets a fresh copied work tree and a log at OUT/logs/attempt-N.log.",
        "USAGE",
        "}",
        "",
        "repo=\"\"",
        "platform=\"Pharo64-13\"",
        "spec=\".smalltalk.ston\"",
        "attempts=\"1\"",
        "out=\"\"",
        "image=\"hpiswa/smalltalkci:24.04\"",
        "include_git=\"false\"",
        "keep_going=\"false\"",
        "",
        "while [ \"$#\" -gt 0 ]; do",
        "  case \"$1\" in",
        "    --repo)",
        "      repo=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --platform)",
        "      platform=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --spec)",
        "      spec=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --attempts)",
        "      attempts=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --out)",
        "      out=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --image)",
        "      image=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --include-git)",
        "      include_git=\"true\"",
        "      shift",
        "      ;;",
        "    --keep-going)",
        "      keep_going=\"true\"",
        "      shift",
        "      ;;",
        "    --help|-h)",
        "      usage",
        "      exit 0",
        "      ;;",
        "    *)",
        "      echo \"Unknown argument: $1\" >&2",
        "      usage >&2",
        "      exit 2",
        "      ;;",
        "  esac",
        "done",
        "",
        "if [ -z \"$repo\" ]; then",
        "  echo \"--repo is required\" >&2",
        "  usage >&2",
        "  exit 2",
        "fi",
        "",
        "if [ ! -d \"$repo\" ]; then",
        "  echo \"Repo directory does not exist: $repo\" >&2",
        "  exit 2",
        "fi",
        "",
        "case \"$attempts\" in",
        "  ''|*[!0-9]*)",
        "    echo \"--attempts must be a positive integer\" >&2",
        "    exit 2",
        "    ;;",
        "esac",
        "",
        "if [ \"$attempts\" -lt 1 ]; then",
        "  echo \"--attempts must be at least 1\" >&2",
        "  exit 2",
        "fi",
        "",
        "if [ -z \"$out\" ]; then",
        "  out=\"/tmp/pharo-ci-repro-$(date +%Y%m%d%H%M%S)\"",
        "fi",
        "",
        "mkdir -p \"$out/logs\"",
        "",
        "echo \"Source: $repo\"",
        "echo \"Platform: $platform\"",
        "echo \"Spec: $spec\"",
        "echo \"Attempts: $attempts\"",
        "echo \"Output: $out\"",
        "echo",
        "",
        "status=0",
        "i=1",
        "while [ \"$i\" -le \"$attempts\" ]; do",
        "  work=\"$out/work-$i\"",
        "  log=\"$out/logs/attempt-$i.log\"",
        "  rm -rf \"$work\"",
        "  mkdir -p \"$work\"",
        "",
        "  if [ \"$include_git\" = \"true\" ]; then",
        "    rsync -a --exclude coverage \"$repo\"/ \"$work\"/",
        "  else",
        "    rsync -a --exclude .git --exclude coverage \"$repo\"/ \"$work\"/",
        "  fi",
        "",
        "  echo \"=== Attempt $i/$attempts ===\"",
        "  echo \"Log: $log\"",
        "",
        "  docker run --rm --platform linux/amd64 \\",
        "    -v \"$work:/work/project\" \\",
        "    -w /work/project \\",
        "    \"$image\" \\",
        "    smalltalkci -s \"$platform\" \"$spec\" 2>&1 | tee \"$log\"",
        "",
        "  attempt_status=\"${PIPESTATUS[0]}\"",
        "  if [ \"$attempt_status\" -ne 0 ]; then",
        "    echo \"Attempt $i failed with status $attempt_status\"",
        "    echo \"Failure log: $log\"",
        "    status=\"$attempt_status\"",
        "    if [ \"$keep_going\" != \"true\" ]; then",
        "      exit \"$status\"",
        "    fi",
        "  else",
        "    echo \"Attempt $i passed\"",
        "  fi",
        "",
        "  i=$((i + 1))",
        "done",
        "",
        "exit \"$status\"",
      ]),
    },
  );
