import type { NexusSkillDefinition } from "dev-nexus";

export const mcpPharoDomainSkillSourceCommit =
  "8ba98ede78404d6a1e3937a8a759022f90c33bde";

const mcpPharoRepositoryUri = "https://github.com/Evref-BL/MCP";

function skillText(lines: string[]): string {
  return `${lines.join("\n")}\n`;
}

function mcpPharoDomainSkill(
  id: string,
  description: string,
  files: Record<string, string>,
): NexusSkillDefinition {
  return {
    manifest: {
      id,
      name: id,
      description,
      version: "0.1.0",
      license: "Apache-2.0",
      source: {
        type: "git",
        uri: `${mcpPharoRepositoryUri}/tree/${mcpPharoDomainSkillSourceCommit}/user/skills/${id}`,
        commit: mcpPharoDomainSkillSourceCommit,
      },
      supportedAgents: ["codex"],
      materialization: "copy",
      sourceControl: "support",
    },
    files,
  };
}

export const mcpPharoDomainSkillPack: readonly NexusSkillDefinition[] = [
  mcpPharoDomainSkill(
    "pharo-ci-repro",
    "Recreate Pharo smalltalkCI and GitHub Actions conditions locally with Docker, capture logs from flaky Pharo CI failures, isolate failing Smalltalk test classes or methods, and distinguish project failures from Pharo VM/Iceberg/libgit2/external-service issues. Use when asked to reproduce, debug, stress, or understand Pharo CI failures locally, especially with smalltalkCI, Docker, Pharo version matrices, intermittent segfaults, or GitHub Actions logs.",
    {
      "SKILL.md": skillText([
        "---",
        "name: pharo-ci-repro",
        "description: Recreate Pharo smalltalkCI and GitHub Actions conditions locally with Docker, capture logs from flaky Pharo CI failures, isolate failing Smalltalk test classes or methods, and distinguish project failures from Pharo VM/Iceberg/libgit2/external-service issues. Use when asked to reproduce, debug, stress, or understand Pharo CI failures locally, especially with smalltalkCI, Docker, Pharo version matrices, intermittent segfaults, or GitHub Actions logs.",
        "---",
        "",
        "# Pharo CI Repro",
        "",
        "## Overview",
        "",
        "Use this skill to reproduce a Pharo CI run locally with Docker and",
        "smalltalkCI, then preserve enough evidence to understand failures that are",
        "hard to diagnose from GitHub logs alone.",
        "",
        "Prefer matching the CI runner first, then narrowing. Do not jump straight to a",
        "hand-written Pharo script unless smalltalkCI itself is not involved in the",
        "failure.",
        "",
        "## Workflow",
        "",
        "1. Identify the CI facts:",
        "   - Pharo platform, for example `Pharo64-13` or `Pharo64-12`.",
        "   - smalltalkCI config path, usually `.smalltalk.ston`.",
        "   - Branch/commit under test.",
        "   - Whether the failure happens during image download, dependency load, project",
        "     load, tests, coverage, or teardown.",
        "",
        "2. Check the local repo state:",
        "   - Run `git status --short --branch`.",
        "   - If reproducing GitHub exactly, use a clean checkout of the failing commit.",
        "   - If testing a local fix, copy the working tree into a scratch directory and",
        "     accept that smalltalkCI may print harmless \"not a git repository\" messages",
        "     if `.git` is excluded.",
        "",
        "3. Run a full local Docker reproduction:",
        "   - Use `scripts/run-smalltalkci-docker.sh` when available.",
        "   - Store logs outside the repo, usually under `/tmp`.",
        "   - Keep the first failing log; do not overwrite it during later narrowing.",
        "",
        "4. Narrow only after one faithful run:",
        "   - Create a temporary `.smalltalk-*.ston` that loads the same baseline but",
        "     runs a single suspect class or package.",
        "   - Repeat the focused run a few times for flakes.",
        "   - Compare crash stacks across failures. For VM crashes, the Smalltalk stack",
        "     just before the native stack is often the clue.",
        "",
        "5. Decide the diagnosis class:",
        "   - Project failure: deterministic Smalltalk failure/error with useful stack.",
        "   - Compatibility failure: load/test failure varies by Pharo version and names",
        "     missing globals/selectors/classes.",
        "   - Native/VM failure: segfault, stack overflow aftermath, or C stack in VM,",
        "     libgit2, FFI, Cairo, etc.",
        "   - External factor: download timeout, GitHub/network/auth/server issue before",
        "     project code runs.",
        "",
        "6. Verify the fix against all relevant Pharo versions before reporting:",
        "   - Run the fixed full suite for every CI platform touched by the change.",
        "   - For flakes, also rerun the focused suspect class/method.",
        "",
        "## Helper Script",
        "",
        "Run:",
        "",
        "```sh",
        "user/skills/pharo-ci-repro/scripts/run-smalltalkci-docker.sh \\",
        "  --repo /path/to/repo \\",
        "  --platform Pharo64-13 \\",
        "  --attempts 3",
        "```",
        "",
        "Useful flags:",
        "",
        "- `--spec .smalltalk-editrepo.ston` to run a focused temporary config.",
        "- `--out /tmp/my-repro` to choose the scratch/log directory.",
        "- `--include-git` to copy `.git` too. Use only for ordinary checkouts, not",
        "  worktrees whose `.git` file points outside the copied tree.",
        "- `--keep-going` to continue after failures and collect several failing logs.",
        "",
        "The script stops at the first failure by default and prints the log path.",
        "",
        "## Pharo-Specific Guidance",
        "",
        "Read `references/pharo-smalltalkci.md` when diagnosing a captured log,",
        "especially for Pharo 13, Iceberg, libgit2, or image/cache issues.",
        "",
        "Watch for these local reproduction traps:",
        "",
        "- The Docker image `hpiswa/smalltalkci:24.04` may run as `linux/amd64`; on Apple",
        "  Silicon, pass Docker's `--platform linux/amd64`.",
        "- Missing SSH keys in Docker often produce Metacello/Iceberg auth warnings and",
        "  HTTPS fallback. That can still match GitHub closely enough if dependencies",
        "  load.",
        "- A scratch copy without `.git` may print Git discovery warnings before Pharo",
        "  starts. Treat them as noise unless the CI failure itself involves Git metadata.",
        "- smalltalkCI can reuse caches inside one container, but separate Docker runs",
        "  usually redownload Pharo images/VMs. This is slower but closer to GitHub.",
        "",
        "## Reporting",
        "",
        "Report:",
        "",
        "- exact command(s) run;",
        "- Pharo image build and VM version from the log;",
        "- first failing phase;",
        "- key Smalltalk and native stack frames;",
        "- log paths;",
        "- what was changed or ruled out;",
        "- verification commands and results.",
        "",
        "Keep conclusions cautious for native crashes. Say \"triggered by our test path\"",
        "when the evidence points to an upstream VM/libgit2 issue but the project can",
        "avoid the unstable path.",
      ]),
      "agents/openai.yaml": skillText([
        "interface:",
        "  display_name: \"Pharo CI Repro\"",
        "  short_description: \"Reproduce Pharo CI locally\"",
        "  default_prompt: \"Use $pharo-ci-repro to recreate a failing Pharo smalltalkCI run locally and capture logs.\"",
      ]),
      "references/pharo-smalltalkci.md": skillText([
        "# Pharo smalltalkCI Log Reading Notes",
        "",
        "Use this reference after a local Docker/smalltalkCI run has produced logs.",
        "",
        "## Phase Boundaries",
        "",
        "smalltalkCI logs usually split into:",
        "",
        "1. Preparing folders.",
        "2. Starting Pharo build.",
        "3. Downloading image and VM.",
        "4. Preparing image and loading SmalltalkCI.",
        "5. Loading project.",
        "6. Testing project.",
        "7. Coverage/upload/teardown.",
        "",
        "If the crash happens after `Testing project...`, project code loaded. If it",
        "happens during `Loading project...`, inspect the last Metacello package loaded",
        "and the first missing global/class/selector.",
        "",
        "## Useful Evidence To Extract",
        "",
        "- `Image Information`, including `Pharo13.1.0SNAPSHOT` or similar.",
        "- Build information SHA.",
        "- VM version, when printed.",
        "- The first test class/method named before a failure.",
        "- The first Smalltalk exception, before any secondary cleanup failure.",
        "- For segfaults, both the native C frames and the Smalltalk frames immediately",
        "  above the crash.",
        "",
        "## Focused Config Pattern",
        "",
        "To narrow a failing class while preserving the same load path, create a",
        "temporary config next to `.smalltalk.ston`:",
        "",
        "```ston",
        "SmalltalkCISpec {",
        "  #loading : [",
        "    SCIMetacelloLoadSpec {",
        "      #baseline : 'MyProject',",
        "      #directory : 'src',",
        "      #ignoreImage : true,",
        "      #onConflict : #useIncoming,",
        "      #onUpgrade : #useIncoming",
        "    }",
        "  ],",
        "  #testing : {",
        "    #classes : [",
        "      #MyProjectSuspectTest",
        "    ],",
        "    #hidePassingTests : true,",
        "    #failOnZeroTests : true",
        "  }",
        "}",
        "```",
        "",
        "Adjust the baseline, directory, and class for the project under test.",
        "",
        "## Pharo 13 / Iceberg / libgit2 Pattern",
        "",
        "In a Pharo MCP investigation on 2026-05-16, a P13 flaky CI crash reproduced",
        "locally inside Docker. It was not a dependency download issue: loading",
        "completed and testing had started.",
        "",
        "Crash signatures included:",
        "",
        "- C stack in `libgit2.so.1.4.4`",
        "- `git_repository_head_unborn`",
        "- `git_commit_lookup`",
        "- Smalltalk frames through `IceLibgitRepository`, `IceRepository>>headCommit`,",
        "  or `IceRepository>>validateCanCommit`",
        "- Test frames in a repository-management test",
        "",
        "The practical mitigation was to avoid unnecessary test-side `repository",
        "headCommit` reads and skip a P13 test that deliberately forced empty libgit2",
        "config values for a P12-only fallback path.",
        "",
        "General lesson: if a Pharo 13 Linux CI segfault points into libgit2 while",
        "testing fresh temporary repositories, treat it as a native stability surface.",
        "Avoid poking Iceberg head/commit metadata in tests unless the assertion is",
        "essential.",
        "",
        "## Interpreting Common Noise",
        "",
        "- `fatal: not a git repository`: often harmless when running smalltalkCI from a",
        "  scratch copy without `.git`. It matters only if the failing behavior depends",
        "  on Git metadata.",
        "- Metacello SSH authentication warnings followed by HTTPS fallback: often",
        "  harmless in Docker if the dependency eventually loads.",
        "- `StackOverflow` after a segfault: often VM aftermath, not the root cause.",
        "- `NewUndeclaredWarning`: can be benign during dependency load, but if it names",
        "  a project class/global required by the current package, investigate.",
        "",
        "## Verification Discipline",
        "",
        "After a fix:",
        "",
        "- Run the failing Pharo platform full suite.",
        "- Run adjacent supported platforms, usually P12 and P13 for MCP.",
        "- Run focused repeats for the flaky class/method if the original failure was",
        "  intermittent.",
        "- Keep the captured failing log path in the report.",
      ]),
      "scripts/run-smalltalkci-docker.sh": skillText([
        "#!/usr/bin/env bash",
        "set -u",
        "",
        "usage() {",
        "  cat <<'USAGE'",
        "Usage:",
        "  run-smalltalkci-docker.sh --repo REPO_DIR [options]",
        "",
        "Options:",
        "  --repo DIR          Source repository or working tree to test.",
        "  --platform NAME    smalltalkCI platform, default Pharo64-13.",
        "  --spec FILE        smalltalkCI spec file, default .smalltalk.ston.",
        "  --attempts N       Number of attempts, default 1.",
        "  --out DIR          Scratch/log directory, default /tmp/pharo-ci-repro-<timestamp>.",
        "  --image IMAGE      Docker image, default hpiswa/smalltalkci:24.04.",
        "  --include-git      Copy .git into each scratch tree.",
        "  --keep-going       Continue after failures instead of stopping at first one.",
        "  --help             Show this help.",
        "",
        "Each attempt gets a fresh copied work tree and a log at OUT/logs/attempt-N.log.",
        "USAGE",
        "}",
        "",
        "repo=\"\"",
        "platform=\"Pharo64-13\"",
        "spec=\".smalltalk.ston\"",
        "attempts=\"1\"",
        "out=\"\"",
        "image=\"hpiswa/smalltalkci:24.04\"",
        "include_git=\"false\"",
        "keep_going=\"false\"",
        "",
        "while [ \"$#\" -gt 0 ]; do",
        "  case \"$1\" in",
        "    --repo)",
        "      repo=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --platform)",
        "      platform=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --spec)",
        "      spec=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --attempts)",
        "      attempts=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --out)",
        "      out=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --image)",
        "      image=\"${2:-}\"",
        "      shift 2",
        "      ;;",
        "    --include-git)",
        "      include_git=\"true\"",
        "      shift",
        "      ;;",
        "    --keep-going)",
        "      keep_going=\"true\"",
        "      shift",
        "      ;;",
        "    --help|-h)",
        "      usage",
        "      exit 0",
        "      ;;",
        "    *)",
        "      echo \"Unknown argument: $1\" >&2",
        "      usage >&2",
        "      exit 2",
        "      ;;",
        "  esac",
        "done",
        "",
        "if [ -z \"$repo\" ]; then",
        "  echo \"--repo is required\" >&2",
        "  usage >&2",
        "  exit 2",
        "fi",
        "",
        "if [ ! -d \"$repo\" ]; then",
        "  echo \"Repo directory does not exist: $repo\" >&2",
        "  exit 2",
        "fi",
        "",
        "case \"$attempts\" in",
        "  ''|*[!0-9]*)",
        "    echo \"--attempts must be a positive integer\" >&2",
        "    exit 2",
        "    ;;",
        "esac",
        "",
        "if [ \"$attempts\" -lt 1 ]; then",
        "  echo \"--attempts must be at least 1\" >&2",
        "  exit 2",
        "fi",
        "",
        "if [ -z \"$out\" ]; then",
        "  out=\"/tmp/pharo-ci-repro-$(date +%Y%m%d%H%M%S)\"",
        "fi",
        "",
        "mkdir -p \"$out/logs\"",
        "",
        "echo \"Source: $repo\"",
        "echo \"Platform: $platform\"",
        "echo \"Spec: $spec\"",
        "echo \"Attempts: $attempts\"",
        "echo \"Output: $out\"",
        "echo",
        "",
        "status=0",
        "i=1",
        "while [ \"$i\" -le \"$attempts\" ]; do",
        "  work=\"$out/work-$i\"",
        "  log=\"$out/logs/attempt-$i.log\"",
        "  rm -rf \"$work\"",
        "  mkdir -p \"$work\"",
        "",
        "  if [ \"$include_git\" = \"true\" ]; then",
        "    rsync -a --exclude coverage \"$repo\"/ \"$work\"/",
        "  else",
        "    rsync -a --exclude .git --exclude coverage \"$repo\"/ \"$work\"/",
        "  fi",
        "",
        "  echo \"=== Attempt $i/$attempts ===\"",
        "  echo \"Log: $log\"",
        "",
        "  docker run --rm --platform linux/amd64 \\",
        "    -v \"$work:/work/project\" \\",
        "    -w /work/project \\",
        "    \"$image\" \\",
        "    smalltalkci -s \"$platform\" \"$spec\" 2>&1 | tee \"$log\"",
        "",
        "  attempt_status=\"${PIPESTATUS[0]}\"",
        "  if [ \"$attempt_status\" -ne 0 ]; then",
        "    echo \"Attempt $i failed with status $attempt_status\"",
        "    echo \"Failure log: $log\"",
        "    status=\"$attempt_status\"",
        "    if [ \"$keep_going\" != \"true\" ]; then",
        "      exit \"$status\"",
        "    fi",
        "  else",
        "    echo \"Attempt $i passed\"",
        "  fi",
        "",
        "  i=$((i + 1))",
        "done",
        "",
        "exit \"$status\"",
      ]),
    },
  ),
  mcpPharoDomainSkill(
    "pharo-image-git-handoff",
    "Turn image-side Pharo changes into clean Tonel/Git changes safely. Use when changes were made in a live Pharo image and need to be exported, reviewed, committed, pushed, or reconciled with Iceberg state; when Iceberg shows detached or dirty repository state; or when diagnosing mismatches between image packages, Tonel files, .project metadata, branches, remotes, and Git diffs.",
    {
      "SKILL.md": skillText([
        "---",
        "name: pharo-image-git-handoff",
        "description: Turn image-side Pharo changes into clean Tonel/Git changes safely. Use when changes were made in a live Pharo image and need to be exported, reviewed, committed, pushed, or reconciled with Iceberg state; when Iceberg shows detached or dirty repository state; or when diagnosing mismatches between image packages, Tonel files, .project metadata, branches, remotes, and Git diffs.",
        "---",
        "",
        "# Pharo Image Git Handoff",
        "",
        "## Mental Model",
        "",
        "Pharo image state, Tonel files, Iceberg working copies, and Git refs are related",
        "but distinct.",
        "",
        "- The image contains the live classes, methods, packages, and repository",
        "  registrations.",
        "- Tonel files are the disk serialization of packages.",
        "- Iceberg tracks package membership, source directory, repository metadata, and",
        "  the image-side loaded version.",
        "- Git tracks files, commits, branches, remotes, and upstreams.",
        "- `.project` records project/package metadata that should agree with the",
        "  Iceberg source directory and disk layout.",
        "",
        "Do not assume that a clean Git worktree means the image is clean, or that an",
        "Iceberg dirty state means Git has file changes.",
        "",
        "## Workflow",
        "",
        "1. Inspect before changing disk:",
        "   - Use Pharo MCP repository tools to list the image-side repository.",
        "   - Check repository name, path, branch, head, upstream, source directory,",
        "     managed packages, modified packages, and missing/detached state.",
        "   - Use shell Git only for disk facts: `git status --short --branch`, `git",
        "     diff`, `git remote -v`, and branch tracking.",
        "",
        "2. Decide whether export is needed:",
        "   - If the task is inspection, summary, or live-image verification, do not",
        "     export.",
        "   - Export only when preparing a real Tonel/Git handoff or when another",
        "     workflow truly needs files on disk.",
        "",
        "3. Preflight the handoff:",
        "   - Confirm the intended repository, branch, remote, source directory, and",
        "     package set.",
        "   - Stop and diagnose detached working copies, missing branch/head, mismatched",
        "     source directory, unexpected package membership, or duplicate repository",
        "     names.",
        "   - If the image-side loaded version is stale but the image contents match",
        "     current Git HEAD, adopting the current commit can be safe; otherwise get",
        "     explicit user judgment.",
        "",
        "4. Export and verify:",
        "   - Export through the Pharo MCP repository tool when possible.",
        "   - After export, re-check image-side repository state.",
        "   - Check `git status --short --branch` and `git diff`.",
        "   - Make sure the diff contains only intended Tonel/project/documentation",
        "     changes.",
        "",
        "5. Commit and push only after review:",
        "   - Do not commit stale image state, wrong-repo changes, unrelated files, or",
        "     generated churn.",
        "   - Commit only after repository identity, branch, remote, source directory,",
        "     package set, and diff all line up.",
        "   - Push only when the user asked for it or clearly approved it.",
        "",
        "## Stop And Diagnose",
        "",
        "Pause before mutating disk or Git history when you see:",
        "",
        "- detached working copy or missing loaded commit;",
        "- missing branch/head/upstream;",
        "- `.project` source directory differs from Iceberg source directory;",
        "- packages loaded in the image are not managed by the repository;",
        "- repository name is duplicated in the image;",
        "- Git branch or remote is not the intended target;",
        "- Git is clean but Iceberg says all packages are modified;",
        "- Iceberg is clean but Git has unexpected Tonel changes.",
        "",
        "## Common Repairs",
        "",
        "Use repairs only when the evidence is strong.",
        "",
        "- Reattach/adopt current HEAD only when loaded package contents match that",
        "  commit.",
        "- Set the Iceberg source directory from `.project` only when the disk layout",
        "  confirms it.",
        "- Re-add managed packages only when they belong to the repository and are",
        "  present under the source directory.",
        "- For wrong remote, wrong branch, duplicate repository, or real divergent",
        "  history, ask the user instead of guessing.",
        "",
        "## Reporting",
        "",
        "Report:",
        "",
        "- image repository state before export;",
        "- whether export was needed and why;",
        "- export action taken;",
        "- image repository state after export;",
        "- Git branch/status and diff summary;",
        "- tests or smoke checks run;",
        "- any unresolved Iceberg/Git ambiguity.",
      ]),
      "agents/openai.yaml": skillText([
        "interface:",
        "  display_name: \"Pharo Image Git Handoff\"",
        "  short_description: \"Export Pharo image changes safely\"",
        "  default_prompt: \"Use $pharo-image-git-handoff to turn these Pharo image changes into clean Tonel/Git changes safely.\"",
      ]),
    },
  ),
  mcpPharoDomainSkill(
    "pharo-project-load",
    "Load Pharo projects into an image from local or remote Tonel/Metacello/Iceberg repositories, choose the correct baseline, branch, source directory, and load group, and diagnose project load failures such as missing BaselineOf packages, wrong src paths, Metacello conflicts, or Pharo-version load differences. Use when asked to load, smoke test, or debug loading a Pharo project in a fresh or existing image.",
    {
      "SKILL.md": skillText([
        "---",
        "name: pharo-project-load",
        "description: Load Pharo projects into an image from local or remote Tonel/Metacello/Iceberg repositories, choose the correct baseline, branch, source directory, and load group, and diagnose project load failures such as missing BaselineOf packages, wrong src paths, Metacello conflicts, or Pharo-version load differences. Use when asked to load, smoke test, or debug loading a Pharo project in a fresh or existing image.",
        "---",
        "",
        "# Pharo Project Load",
        "",
        "## Overview",
        "",
        "Use this skill when the task is to load a Pharo project into an image, especially",
        "from a Tonel repository with a `src` directory or when reproducing how CI/users",
        "load the project.",
        "",
        "Prefer the Pharo MCP tools when a live image is available. Use Smalltalk snippets",
        "only when no dedicated tool fits.",
        "",
        "## Workflow",
        "",
        "1. Identify the load target:",
        "   - Pharo version.",
        "   - Repository URL or local path.",
        "   - Branch, tag, or commit.",
        "   - Source directory, usually `src`.",
        "   - Baseline name, without the `BaselineOf` prefix.",
        "   - Load group, if one is truly needed.",
        "",
        "2. Inspect the repository layout before loading:",
        "   - Confirm where `BaselineOf<name>` lives.",
        "   - Confirm that Tonel package directories are under the selected source",
        "     directory.",
        "   - Check `.smalltalk.ston` or project docs for the CI load path.",
        "   - If the repo recently moved to `src`, make sure URLs and `.project`",
        "     metadata agree.",
        "",
        "3. Load the project:",
        "   - With Pharo MCP, use `load_repository` for remote Metacello loads.",
        "   - For local Tonel paths, evaluate a small Metacello snippet if needed.",
        "   - Prefer the default load first. Specify groups only when the task or project",
        "     docs require them.",
        "",
        "4. Verify the image:",
        "   - List loaded packages/classes with MCP tools.",
        "   - Run focused tests or the project test package when present.",
        "   - Check Iceberg repository state if the task cares about later edits.",
        "",
        "5. Diagnose failures by phase:",
        "   - Baseline/package not found: branch or source directory is wrong, or the",
        "     baseline package is not committed where Metacello is looking.",
        "   - Undeclared globals/selectors during load: target Pharo version lacks an API",
        "     expected by the project or one of its dependencies.",
        "   - Metacello conflict/upgrade failure: dependency registration differs from",
        "     the image state; use the simplest conflict policy that exists in the target",
        "     Pharo version.",
        "   - Native crash during load: rerun once, then use the `pharo-ci-repro` skill",
        "     if smalltalkCI/Docker conditions matter.",
        "",
        "## Examples",
        "",
        "Remote Tonel repository:",
        "",
        "```smalltalk",
        "Metacello new",
        "  baseline: 'MyProject';",
        "  repository: 'github://Owner/MyProject:main/src';",
        "  load",
        "```",
        "",
        "Local Tonel repository:",
        "",
        "```smalltalk",
        "Metacello new",
        "  baseline: 'MyProject';",
        "  repository: 'tonel:///absolute/path/to/MyProject/src';",
        "  load",
        "```",
        "",
        "Explicit group, only when needed:",
        "",
        "```smalltalk",
        "Metacello new",
        "  baseline: 'MyProject';",
        "  repository: 'github://Owner/MyProject:main/src';",
        "  load: 'Tests'",
        "```",
        "",
        "## Common Checks",
        "",
        "- `NotFound: BaselineOfMyProject` usually means Metacello is looking in the",
        "  wrong source directory or branch.",
        "- If the project uses `src`, the repository URL usually needs to end in `/src`.",
        "- The branch in the URL should match the branch containing the desired layout.",
        "- Do not assume Metacello helper selectors exist in every supported Pharo",
        "  version; prefer plain `load` unless a compatibility wrapper is already",
        "  provided.",
        "- When using a local path, use an absolute path to avoid command-line working",
        "  directory surprises.",
        "",
        "## Reporting",
        "",
        "Report the Pharo version, repository path/URL, branch, source directory,",
        "baseline, group, load result, verification result, and the first meaningful",
        "error if loading failed.",
      ]),
      "agents/openai.yaml": skillText([
        "interface:",
        "  display_name: \"Pharo Project Load\"",
        "  short_description: \"Load Pharo Tonel projects\"",
        "  default_prompt: \"Use $pharo-project-load to load this Pharo project into an image and diagnose any Metacello or Tonel load failures.\"",
      ]),
    },
  ),
  mcpPharoDomainSkill(
    "pharo-version-compat",
    "Use PharoCompatibility to make a Pharo project run across supported Pharo versions, especially when a project developed against one Pharo API surface must load on another. Use when adding PharoCompatibility to a baseline, diagnosing missing globals/selectors/classes across Pharo versions, deciding between shims and project abstractions, or extending PharoCompatibility with general per-Pharo-version compatibility behavior.",
    {
      "SKILL.md": skillText([
        "---",
        "name: pharo-version-compat",
        "description: Use PharoCompatibility to make a Pharo project run across supported Pharo versions, especially when a project developed against one Pharo API surface must load on another. Use when adding PharoCompatibility to a baseline, diagnosing missing globals/selectors/classes across Pharo versions, deciding between shims and project abstractions, or extending PharoCompatibility with general per-Pharo-version compatibility behavior.",
        "---",
        "",
        "# Pharo Version Compatibility",
        "",
        "## Mental Model",
        "",
        "`PharoCompatibility` is for Pharo-version compatibility, not per-library shims.",
        "A consuming project declares the Pharo API surface its source expects, then the",
        "library loads the runtime-specific compatibility packages needed by the image.",
        "",
        "Current public surfaces include:",
        "",
        "- `Pharo12Surface`: for projects whose source expects the Pharo 12 API surface.",
        "- `Pharo13Surface`: for projects whose source expects the Pharo 13 API surface.",
        "",
        "Omit `loads:` only when the project needs the core helper API but no surface.",
        "",
        "## Baseline Examples",
        "",
        "Project source expects the Pharo 12 surface:",
        "",
        "```smalltalk",
        "spec",
        "  baseline: 'PharoCompatibility'",
        "  with: [",
        "    spec",
        "      repository: 'github://Evref-BL/PharoCompatibility:main/src';",
        "      loads: #( 'Pharo12Surface' ) ]",
        "```",
        "",
        "Project source expects the Pharo 13 surface:",
        "",
        "```smalltalk",
        "spec",
        "  baseline: 'PharoCompatibility'",
        "  with: [",
        "    spec",
        "      repository: 'github://Evref-BL/PharoCompatibility:main/src';",
        "      loads: #( 'Pharo13Surface' ) ]",
        "```",
        "",
        "Require `PharoCompatibility` from packages that use its APIs.",
        "",
        "## Consumer Workflow",
        "",
        "1. Identify the source surface:",
        "   - Which Pharo version is the project developed against?",
        "   - Which Pharo versions should load it?",
        "",
        "2. Add the matching `PharoCompatibility` surface to the baseline.",
        "",
        "3. Load and test on every supported Pharo version.",
        "",
        "4. Classify failures:",
        "   - missing global/class;",
        "   - missing selector;",
        "   - renamed class or package;",
        "   - semantic API change;",
        "   - deprecation/notice behavior difference;",
        "   - native/tooling failure outside ordinary compatibility.",
        "",
        "5. Choose the fix:",
        "   - Transparent shim for equivalent globals, classes, or selectors.",
        "   - Explicit `PharoCompatibility` helper API for behavior multiple projects",
        "     can share.",
        "   - Project abstraction when behavior differs and cannot be hidden safely.",
        "   - Project-local fix when the issue is specific to that library.",
        "",
        "6. Verify both the compatibility library and the consuming project.",
        "",
        "## Existing Helper APIs",
        "",
        "Useful current helpers include:",
        "",
        "- `PharoCompatibility resumeDeprecationsDuring:`",
        "- `PharoCompatibility withNonInteractiveAuthorNamed:during:`",
        "- `PharoCompatibility syntaxErrorNoticeClassName`",
        "- `PharoCompatibility loadedSurfaces`",
        "- `PharoCompatibility runtimeVersionString`",
        "",
        "Use helpers for behavior that should be explicit. Use transparent shims only",
        "when the old and new contracts are equivalent.",
        "",
        "## Extending PharoCompatibility",
        "",
        "When a Pharo-version difference is not handled yet:",
        "",
        "1. Confirm it is a general Pharo version difference, not a project-specific",
        "   workaround.",
        "2. Decide which source surface needs support and which runtime image is missing",
        "   it.",
        "3. Put runtime-specific code in a matching package, such as",
        "   `PharoCompatibility-Pharo13Surface-Pharo12`.",
        "4. Extend the baseline group conditionally for the affected Pharo versions.",
        "5. Add installer behavior only when globals or startup aliases must be created",
        "   after load.",
        "6. Guard optional classes with late lookup through `Smalltalk at:ifAbsent:`.",
        "7. Add tests for the compatibility surface contract, not only that packages",
        "   load.",
        "",
        "Keep shims additive when possible. Avoid changing existing runtime behavior",
        "unless there is no safer compatibility path.",
        "",
        "## Known Difference Shapes",
        "",
        "The current library already handles examples like:",
        "",
        "- syntax error notice class name differences;",
        "- RB/Re refactoring class renames;",
        "- `Author` availability and non-interactive author handling;",
        "- legacy `FileStream` binding when a P13-shaped project loads on older Pharo;",
        "- semaphore timeout protocol compatibility.",
        "",
        "These are examples, not a closed list.",
        "",
        "## Verification",
        "",
        "- Run `PharoCompatibility` tests across the supported Pharo matrix.",
        "- Run the consuming project's tests across the same matrix.",
        "- Use `pharo-project-load` for load or baseline failures.",
        "- Use `pharo-ci-repro` for smalltalkCI/GitHub CI reproduction.",
        "- Keep P12/P13 or newer/older directions separate in the diagnosis; a forward",
        "  shim and a backward shim may need different fixes.",
      ]),
      "agents/openai.yaml": skillText([
        "interface:",
        "  display_name: \"Pharo Version Compatibility\"",
        "  short_description: \"Use PharoCompatibility surfaces\"",
        "  default_prompt: \"Use $pharo-version-compat to make this Pharo project compatible across supported Pharo versions with PharoCompatibility.\"",
      ]),
    },
  ),
];
