import fs from "node:fs";
import path from "node:path";
import { safePathToken } from "./pathTokens.js";

export type PharoLoadRepositoryRole = "project" | "dependency";

export interface PharoLoadRepositorySpec {
  id?: string;
  baseline: string;
  sourceRoot: string;
  sourceDirectory?: string;
  loads?: readonly string[];
}

export interface PreparePharoProjectLoadWorkspaceOptions {
  workspaceRoot: string;
  project: PharoLoadRepositorySpec;
  dependencies?: readonly PharoLoadRepositorySpec[];
  repositoriesDirectoryName?: string;
  scriptFileName?: string;
  metadataFileName?: string;
}

export interface PreparedPharoLoadRepository {
  role: PharoLoadRepositoryRole;
  id: string;
  baseline: string;
  sourceRoot: string;
  sourceDirectory: string;
  stagedRoot: string;
  stagedSourceDirectory: string;
  baselinePath: string;
  loads: string[];
}

export interface MissingPharoLoadRepository {
  role: PharoLoadRepositoryRole;
  id: string;
  baseline: string;
  sourceRoot: string;
  sourceDirectory: string;
  expectedBaselinePath: string;
}

export interface PreparePharoProjectLoadWorkspaceResult {
  ready: boolean;
  workspaceRoot: string;
  repositoriesRoot: string;
  scriptPath: string;
  metadataPath: string;
  repositories: PreparedPharoLoadRepository[];
  missing: MissingPharoLoadRepository[];
  scriptSource: string | null;
}

export class PharoProjectLoadWorkspaceError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PharoProjectLoadWorkspaceError";
  }
}

const defaultRepositoriesDirectoryName = "repositories";
const defaultScriptFileName = "load-local-project.st";
const defaultMetadataFileName = "load-local-project.json";
const defaultSourceDirectory = "src";

const generatedRepositoryExcludes = new Set([
  ".git",
  ".dev-nexus",
  ".codex",
  "node_modules",
  "worktrees",
]);

function requiredNonEmpty(value: string, pathName: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    throw new PharoProjectLoadWorkspaceError(`${pathName} must be a non-empty string`);
  }

  return trimmed;
}

function assertInside(parent: string, child: string, pathName: string): void {
  const relative = path.relative(parent, child);
  if (relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative))) {
    return;
  }

  throw new PharoProjectLoadWorkspaceError(
    `${pathName} must resolve inside the load workspace: ${child}`,
  );
}

function smalltalkString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function smalltalkArray(values: readonly string[]): string {
  return `#( ${values.map(smalltalkString).join(" ")} )`;
}

function normalizeRepositorySpec(
  spec: PharoLoadRepositorySpec,
  role: PharoLoadRepositoryRole,
): Omit<PreparedPharoLoadRepository, "stagedRoot" | "stagedSourceDirectory"> {
  const baseline = requiredNonEmpty(spec.baseline, `${role}.baseline`);
  const sourceRoot = path.resolve(requiredNonEmpty(spec.sourceRoot, `${role}.sourceRoot`));
  const sourceDirectory = spec.sourceDirectory
    ? requiredNonEmpty(spec.sourceDirectory, `${role}.sourceDirectory`)
    : defaultSourceDirectory;
  const id = safePathToken(spec.id ?? baseline, { fallback: "repository" });
  const baselinePath = path.join(
    sourceRoot,
    sourceDirectory,
    `BaselineOf${baseline}`,
    `BaselineOf${baseline}.class.st`,
  );

  return {
    role,
    id,
    baseline,
    sourceRoot,
    sourceDirectory,
    baselinePath,
    loads: [...(spec.loads ?? [])],
  };
}

function copyDirectory(source: string, target: string): void {
  fs.rmSync(target, { recursive: true, force: true });
  fs.cpSync(source, target, {
    recursive: true,
    dereference: false,
    filter: (sourcePath) => {
      const name = path.basename(sourcePath);
      if (generatedRepositoryExcludes.has(name)) {
        return false;
      }

      return true;
    },
  });
}

export function pharoTonelRepositoryUrl(sourceDirectory: string): string {
  return `tonel://${path.resolve(sourceDirectory).replaceAll("\\", "/")}`;
}

export function pharoMetacelloLoadSource(
  repositories: readonly PreparedPharoLoadRepository[],
): string {
  return [
    '"Generated by DevNexus-Pharo. Load declared dependencies before the project from local Tonel repositories."',
    ...repositories.flatMap((repository) => {
      const lines = [
        "Metacello new",
        `  baseline: ${smalltalkString(repository.baseline)};`,
        `  repository: ${smalltalkString(pharoTonelRepositoryUrl(repository.stagedSourceDirectory))};`,
        "  onConflictUseIncoming;",
        "  onUpgrade: [ :ex :loaded :incoming | ex useIncoming ];",
      ];
      if (repository.loads.length > 0) {
        lines.push(`  load: ${smalltalkArray(repository.loads)}.`);
      } else {
        lines.push("  load.");
      }

      return [...lines, ""];
    }),
  ].join("\n");
}

export function preparePharoProjectLoadWorkspace(
  options: PreparePharoProjectLoadWorkspaceOptions,
): PreparePharoProjectLoadWorkspaceResult {
  const workspaceRoot = path.resolve(
    requiredNonEmpty(options.workspaceRoot, "workspaceRoot"),
  );
  const repositoriesRoot = path.join(
    workspaceRoot,
    options.repositoriesDirectoryName ?? defaultRepositoriesDirectoryName,
  );
  const scriptPath = path.join(
    workspaceRoot,
    options.scriptFileName ?? defaultScriptFileName,
  );
  const metadataPath = path.join(
    workspaceRoot,
    options.metadataFileName ?? defaultMetadataFileName,
  );
  assertInside(workspaceRoot, repositoriesRoot, "repositoriesRoot");
  assertInside(workspaceRoot, scriptPath, "scriptPath");
  assertInside(workspaceRoot, metadataPath, "metadataPath");

  const normalized = [
    ...(options.dependencies ?? []).map((dependency) =>
      normalizeRepositorySpec(dependency, "dependency"),
    ),
    normalizeRepositorySpec(options.project, "project"),
  ];
  const seenIds = new Set<string>();
  for (const repository of normalized) {
    if (seenIds.has(repository.id)) {
      throw new PharoProjectLoadWorkspaceError(
        `Duplicate Pharo load repository id: ${repository.id}`,
      );
    }
    seenIds.add(repository.id);
  }

  const missing = normalized
    .filter((repository) => !fs.existsSync(repository.baselinePath))
    .map((repository): MissingPharoLoadRepository => ({
      role: repository.role,
      id: repository.id,
      baseline: repository.baseline,
      sourceRoot: repository.sourceRoot,
      sourceDirectory: repository.sourceDirectory,
      expectedBaselinePath: repository.baselinePath,
    }));

  if (missing.length > 0) {
    return {
      ready: false,
      workspaceRoot,
      repositoriesRoot,
      scriptPath,
      metadataPath,
      repositories: [],
      missing,
      scriptSource: null,
    };
  }

  fs.mkdirSync(repositoriesRoot, { recursive: true });
  const repositories = normalized.map((repository): PreparedPharoLoadRepository => {
    const stagedRoot = path.join(repositoriesRoot, repository.id);
    assertInside(repositoriesRoot, stagedRoot, `${repository.id}.stagedRoot`);
    copyDirectory(repository.sourceRoot, stagedRoot);
    const stagedSourceDirectory = path.join(stagedRoot, repository.sourceDirectory);
    return {
      ...repository,
      stagedRoot,
      stagedSourceDirectory,
    };
  });
  const scriptSource = pharoMetacelloLoadSource(repositories);
  fs.mkdirSync(path.dirname(scriptPath), { recursive: true });
  fs.writeFileSync(scriptPath, scriptSource, "utf8");
  fs.writeFileSync(
    metadataPath,
    `${JSON.stringify(
      {
        version: 1,
        generatedBy: "dev-nexus-pharo",
        workspaceRoot,
        repositories,
        scriptPath,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );

  return {
    ready: true,
    workspaceRoot,
    repositoriesRoot,
    scriptPath,
    metadataPath,
    repositories,
    missing: [],
    scriptSource,
  };
}
