import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import fs from "node:fs";
import { type VibeKanbanBackendConfig } from "./config.js";
import { readEnvValue, setEnvValue, stripUtf8Bom } from "./envFile.js";

function randomSecret(byteLength = 48): string {
  return randomBytes(byteLength).toString("base64");
}

function firstEnvValue(
  env: NodeJS.ProcessEnv,
  names: readonly string[],
): string | undefined {
  for (const name of names) {
    const value = env[name];
    if (value && value.trim().length > 0) {
      return value.trim();
    }
  }

  return undefined;
}

function gitConfigValue(key: string): string | undefined {
  const result = spawnSync("git", ["config", "--global", "--get", key], {
    encoding: "utf8",
    shell: false,
    timeout: 5_000,
    windowsHide: true,
  });
  if (result.status !== 0) {
    return undefined;
  }

  const value = result.stdout.trim();
  return value.length > 0 ? value : undefined;
}

function localAuthEmail(env: NodeJS.ProcessEnv = process.env): string {
  return (
    firstEnvValue(env, [
      "DEV_NEXUS_PHARO_VIBE_LOCAL_AUTH_EMAIL",
      "DEV_NEXUS_PHARO_GIT_USER_EMAIL",
      "GIT_AUTHOR_EMAIL",
      "GIT_COMMITTER_EMAIL",
    ]) ??
    gitConfigValue("user.email") ??
    "admin@dev-nexus-pharo.local"
  );
}

function githubOAuthCredentials(env: NodeJS.ProcessEnv = process.env):
  | {
      clientId: string;
      clientSecret: string;
    }
  | undefined {
  const clientId = firstEnvValue(env, [
    "DEV_NEXUS_PHARO_GITHUB_OAUTH_CLIENT_ID",
    "GITHUB_OAUTH_CLIENT_ID",
  ]);
  const clientSecret = firstEnvValue(env, [
    "DEV_NEXUS_PHARO_GITHUB_OAUTH_CLIENT_SECRET",
    "GITHUB_OAUTH_CLIENT_SECRET",
  ]);

  if (!clientId || !clientSecret) {
    return undefined;
  }

  return { clientId, clientSecret };
}

export function localBackendPort(
  config: Pick<VibeKanbanBackendConfig, "sharedApiBase">,
): string {
  try {
    const parsed = new URL(config.sharedApiBase);
    return parsed.port || (parsed.protocol === "https:" ? "443" : "80");
  } catch {
    return "3100";
  }
}

export function localBackendHost(
  config: Pick<VibeKanbanBackendConfig, "sharedApiBase">,
): string {
  try {
    return new URL(config.sharedApiBase).hostname || "127.0.0.1";
  } catch {
    return "127.0.0.1";
  }
}

export function defaultEnvRemoteContent(
  config: Pick<VibeKanbanBackendConfig, "sharedApiBase">,
  options: { bindHost?: string } = {},
): string {
  const port = localBackendPort(config);
  const host = options.bindHost ?? localBackendHost(config);
  const localAuthPassword = randomSecret(24);
  const githubOAuth = githubOAuthCredentials();

  return [
    "# Generated by DevNexus-Pharo. Do not commit this file.",
    `VIBEKANBAN_REMOTE_JWT_SECRET=${randomSecret(48)}`,
    `ELECTRIC_ROLE_PASSWORD=${randomSecret(32)}`,
    `DB_PASSWORD=${randomSecret(32)}`,
    `PUBLIC_BASE_URL=${config.sharedApiBase}`,
    `REMOTE_SERVER_PORTS=${host}:${port}:8081`,
    "VITE_RELAY_API_BASE_URL=http://127.0.0.1:8082",
    `GITHUB_OAUTH_CLIENT_ID=${githubOAuth?.clientId ?? ""}`,
    `GITHUB_OAUTH_CLIENT_SECRET=${githubOAuth?.clientSecret ?? ""}`,
    "GOOGLE_OAUTH_CLIENT_ID=",
    "GOOGLE_OAUTH_CLIENT_SECRET=",
    `SELF_HOST_LOCAL_AUTH_EMAIL=${localAuthEmail()}`,
    `SELF_HOST_LOCAL_AUTH_PASSWORD=${localAuthPassword}`,
    "LOOPS_EMAIL_API_KEY=",
    "LOOPS_INVITE_TEMPLATE_ID=cmhvy2wgs3s13z70i1pxakij9",
    "LOOPS_REVIEW_READY_TEMPLATE_ID=cmj47k5ge16990iylued9by17",
    "LOOPS_REVIEW_FAILED_TEMPLATE_ID=cmj49ougk1c8s0iznavijdqpo",
    "AZURE_STORAGE_ACCOUNT_NAME=",
    "AZURE_STORAGE_ACCOUNT_KEY=",
    "AZURE_STORAGE_CONTAINER_NAME=issue-attachments",
    "AZURE_STORAGE_ENDPOINT_URL=",
    "AZURE_STORAGE_PUBLIC_ENDPOINT_URL=",
    "",
  ].join("\n");
}

export function syncAuthDefaultsIntoEnvFile(envFile: string): boolean {
  if (!fs.existsSync(envFile)) {
    return false;
  }

  let content = stripUtf8Bom(fs.readFileSync(envFile, "utf8"));
  let changed = false;
  const githubOAuth = githubOAuthCredentials();

  if (
    githubOAuth &&
    !readEnvValue(content, "GITHUB_OAUTH_CLIENT_ID") &&
    !readEnvValue(content, "GITHUB_OAUTH_CLIENT_SECRET")
  ) {
    let update = setEnvValue(
      content,
      "GITHUB_OAUTH_CLIENT_ID",
      githubOAuth.clientId,
    );
    content = update.content;
    changed ||= update.changed;
    update = setEnvValue(
      content,
      "GITHUB_OAUTH_CLIENT_SECRET",
      githubOAuth.clientSecret,
    );
    content = update.content;
    changed ||= update.changed;
  }

  if (
    readEnvValue(content, "SELF_HOST_LOCAL_AUTH_EMAIL") ===
    "admin@dev-nexus-pharo.local"
  ) {
    const email = localAuthEmail();
    if (email !== "admin@dev-nexus-pharo.local") {
      const update = setEnvValue(content, "SELF_HOST_LOCAL_AUTH_EMAIL", email);
      content = update.content;
      changed ||= update.changed;
    }
  }

  if (changed) {
    fs.writeFileSync(
      envFile,
      content.endsWith("\n") ? content : `${content}\n`,
      "utf8",
    );
  }

  return changed;
}
